'use client'

import { useState } from 'react'
import { Button } from '@/components/ui/button'
import { RefreshCw, Sparkles, Download } from 'lucide-react'
import type { Poll, AiAnalysis, PollQuestion } from '@/lib/supabase/types'

interface Props {
  poll: Poll
  questions: PollQuestion[]
  responses: { id: string; contact_id: string; question_id: string; answer: string; received_at: string }[]
  initialAnalysis: AiAnalysis | null
}

const SECTION_ORDER = [
  '## Executive Summary',
  '## Key Voter Segments',
  '## Messaging Recommendations',
  '## Outreach Priorities',
  '## Risks & Counterintuitive Findings',
]

function parseMemo(text: string): { heading: string; body: string }[] {
  const sections: { heading: string; body: string }[] = []
  let current: { heading: string; body: string } | null = null

  for (const line of text.split('\n')) {
    if (line.startsWith('## ')) {
      if (current) sections.push(current)
      current = { heading: line.replace('## ', '').trim(), body: '' }
    } else if (current) {
      current.body += line + '\n'
    }
  }
  if (current) sections.push(current)
  return sections
}

export default function InsightsTab({ poll, initialAnalysis }: Props) {
  const initialInsights = typeof initialAnalysis?.insights === 'string'
    ? initialAnalysis.insights
    : null
  const [insights, setInsights] = useState<string | null>(initialInsights)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')

  async function generate() {
    setLoading(true)
    setError('')
    try {
      const res = await fetch('/api/ai/insights', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ poll_id: poll.id }),
      })
      const data = await res.json()
      if (!res.ok) throw new Error(data.error ?? 'Failed to generate insights')
      setInsights(data.insights)
    } catch (e: any) {
      setError(e.message)
    } finally {
      setLoading(false)
    }
  }

  function exportPDF() {
    if (!insights) return
    const win = window.open('', '_blank')
    if (!win) return
    win.document.write(`
      <html>
        <head>
          <title>${poll.title} — Strategic Memo</title>
          <style>
            body { font-family: Georgia, serif; max-width: 700px; margin: 40px auto; color: #111; line-height: 1.6; }
            h1 { font-size: 24px; margin-bottom: 4px; }
            h2 { font-size: 18px; margin-top: 32px; border-bottom: 1px solid #ddd; padding-bottom: 4px; }
            p { margin: 12px 0; }
          </style>
        </head>
        <body>
          <h1>${poll.title} — Strategic Intelligence Memo</h1>
          <p style="color: #666; font-size: 14px;">Generated by CampaignAnalyzer • ${new Date().toLocaleDateString()}</p>
          ${insights.replace(/## (.+)/g, '<h2>$1</h2>').replace(/\n\n/g, '</p><p>').replace(/\n/g, '<br/>')}
        </body>
      </html>
    `)
    win.document.close()
    win.print()
  }

  const sections = insights ? parseMemo(insights) : []

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="font-serif text-xl text-white">Strategic Intelligence Memo</h2>
          <p className="text-sm text-white/40 mt-1">
            Claude acts as a senior political strategist to write an actionable campaign memo
          </p>
        </div>
        <div className="flex gap-2">
          {insights && (
            <Button variant="outline" onClick={exportPDF}>
              <Download className="h-4 w-4 mr-2" />
              Export PDF
            </Button>
          )}
          <Button onClick={generate} disabled={loading} variant={insights ? 'outline' : 'default'}>
            {loading ? (
              <><RefreshCw className="h-4 w-4 mr-2 animate-spin" />Writing memo…</>
            ) : insights ? (
              <><RefreshCw className="h-4 w-4 mr-2" />Regenerate</>
            ) : (
              <><Sparkles className="h-4 w-4 mr-2" />Generate Insights</>
            )}
          </Button>
        </div>
      </div>

      {error && (
        <div className="rounded-lg border border-red-500/30 bg-red-500/10 px-4 py-3 text-sm text-red-400">
          {error}
        </div>
      )}

      {loading && (
        <div className="rounded-xl border border-white/10 bg-white/5 p-12 text-center">
          <RefreshCw className="h-8 w-8 text-blue-400 animate-spin mx-auto mb-4" />
          <p className="text-white/40 text-sm">Claude is writing your strategic memo…</p>
          <p className="text-white/20 text-xs mt-1">This typically takes 15–30 seconds</p>
        </div>
      )}

      {!loading && !insights && (
        <div className="rounded-xl border border-white/10 bg-white/5 p-12 text-center">
          <Sparkles className="h-10 w-10 text-white/20 mx-auto mb-4" />
          <p className="text-white/40 text-sm">No strategic memo generated yet</p>
          <p className="text-white/20 text-xs mt-1">Click "Generate Insights" to produce a full campaign strategy memo</p>
        </div>
      )}

      {!loading && sections.length > 0 && (
        <div className="rounded-xl border border-white/10 bg-white/5 overflow-hidden">
          <div className="bg-[#0f1f38] border-b border-white/10 px-6 py-4">
            <h1 className="font-serif text-xl text-white">{poll.title}</h1>
            <p className="text-xs text-white/40 mt-1">Strategic Intelligence Memo — {new Date().toLocaleDateString()}</p>
          </div>
          <div className="p-6 space-y-8">
            {sections.map((s, i) => (
              <div key={i}>
                <h2 className="font-serif text-lg text-white border-b border-white/10 pb-2 mb-4">{s.heading}</h2>
                <div className="text-sm text-white/70 leading-relaxed whitespace-pre-wrap">{s.body.trim()}</div>
              </div>
            ))}
          </div>
        </div>
      )}

      {!loading && insights && sections.length === 0 && (
        <div className="rounded-xl border border-white/10 bg-white/5 p-6">
          <div className="text-sm text-white/70 leading-relaxed whitespace-pre-wrap">{insights}</div>
        </div>
      )}
    </div>
  )
}
